# Docker image
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'terraform-azurerm-postgresql:$(build.buildId)'

steps:
- script: bash test.sh $(client_id) $(client_secret) $(system.debug) $SECRET_CLIENT_ID
  displayName: 'build'

- script: env
  display name: "env"
