pool:
  vmImage: 'Ubuntu 16.04'

variables:
  SAMPLE_VARIABLE: 'test-value'

steps:
- script: 'echo "Script: ${SAMPLE_VARIABLE}"'
  displayName: Pipeline
- script: bash test.sh
  displayName: 'Script'
