pool:
  vmImage: 'Ubuntu 16.04'

variables:
- group: SampleGroup
- group: SampleGroupVars
- name: NEW_ENV
  value: $(new-env)
- name: NEW_ENV_VARS
  value: $(new-env-vars)

steps:
- script: 'echo "NEW_ENV: ${NEW_ENV}" && echo "new-env: $(new-env)" && Necho "NEW_ENV_VARS: ${NEW_ENV_VARS}" && echo "new-env-vars: $(new-env-vars)"'
#- script: 'echo "Script: ${SAMPLE_VARIABLE}"'
#  displayName: Pipeline
#- script: bash test.sh
#  displayName: 'Script'
