variables:
- group: SampleGroup
- group: SampleGroupVars

jobs:
- job: test_job
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    NEW_ENV: $(new-env)

  steps:
  - script: 'echo "NEW_ENV: ${NEW_ENV}" && echo "new-env: $(NEW-ENV)" && echo "new-env{}: ${new-env}" && echo "NEW_ENV_VARS: ${NEW_ENV_VARS}" && echo "new-env-vars: $(new-env-vars)" && echo "new-env-vars{}: ${new-env-vars}"'
#    env: 
#      NEW_ENV: $(new-env)
#- script: 'echo "Script: ${SAMPLE_VARIABLE}"'
#  displayName: Pipeline
#- script: bash test.sh
#  displayName: 'Script'
