pool:
  vmImage: 'Ubuntu 16.04'

variables:
- group: SampleGroup
- name: NEW_ENV
  value: $(new-env)

steps:
- script: 'echo "Variable: ${NEW_ENV}"'
#- script: 'echo "Script: ${SAMPLE_VARIABLE}"'
#  displayName: Pipeline
#- script: bash test.sh
#  displayName: 'Script'
